### ISSUE TITLE
Page numbering

### ISSUE THREAD

**Issue by happyrabbit** [happyrabbit/IntroDataScience#4]
Where can I change the setting of page number to be arabic for main content? 

http://scientistcafe.com/IDS/IDS.pdf

@yihui

**Comment by happyrabbit** [comment]
Fixed.
Need to insert "\mainmatter" before the first chapter of the book

我简直骄傲的不要不要的，哈哈

**Comment by yihui** [comment]
偷看我的答案了吗？https://github.com/rstudio/bookdown/blame/master/inst/examples/01-introduction.Rmd#L1

**Comment by happyrabbit** [comment]
@yihui 啧啧啧啧......你这么自恋，你儿子知道么？.............................是的，我看了你的标准答案，妥妥哒！

对了，\renewenvironment{Shaded}{\begin{kframe}}{\end{kframe}} 这个Shaded environment去哪里找？我给注释掉了，不然一直会有问题。

**Comment by yihui** [comment]
如果注释掉能生成 PDF 的话你就注释掉吧。这个环境是 Pandoc 生成的，只有在文中有高亮代码块的时候才会出现。
